name = "lazzlek-api"
workers_dev = true
compatibility_date = "2023-01-01"
main = "src/index.js"

[durable_objects]
bindings = [
    { name = "rooms", class_name = "ChatRoom" },
    { name = "limiters", class_name = "RateLimiter" },
]

[env.staging.vars]
API_HOST = "staging.example.com"

[env.production.vars]
API_HOST = "master.example.com"


# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v2"                                # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]
