name = "lazzlek-api"
workers_dev = true
compatibility_date = "2023-01-01"
main = "src/index.ts"
minify = true
account_id = "556675f35212283cadf2ad1dbb0da3f0"


[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false


[env.production.durable_objects]
bindings = [
    { name = "rooms", class_name = "ChatRoom" },
    { name = "limiters", class_name = "RateLimiter" },
]
[env.production.migrations]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]


[env.staging.durable_objects]
bindings = [
    { name = "rooms", class_name = "ChatRoom" },
    { name = "limiters", class_name = "RateLimiter" },
]
[env.staging.migrations]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]
